export const data = {
    'Y 4#3': {
        regionName: 'Y 4#3',
        questsNumber: 1426,
        successQuestsNumber: 1154,
        expirience: 7745,
        gold: 7702,
        resources: {
            Pelt: 558,
            Cloth: 475,
            'Mutton Cut': 361,
            Thread: 264,
            Wrapping: 172,
            'Lamb Fillet': 139,
            'Superior Mutton Slice': 35,
            Stick: 18,
        },
    },
    'Y 3#4': {
        regionName: 'Y 3#4',
        questsNumber: 598,
        successQuestsNumber: 481,
        expirience: 3342,
        gold: 2037,
        resources: {
            Coal: 186,
            'Iron Ore': 179,
            Powder: 121,
            Wrapping: 36,
            'Scroll of Escape': 27,
            Stick: 8,
        },
    },
    'Y 3#2': {
        regionName: 'Y 3#2',
        questsNumber: 478,
        successQuestsNumber: 391,
        expirience: 2611,
        gold: 1981,
        resources: {
            Charcoal: 233,
            Stick: 228,
            'Wooden arrow': 212,
            Bone: 93,
            Wrapping: 16,
        },
    },
    'Y 2#3': {
        regionName: 'Y 2#3',
        questsNumber: 435,
        successQuestsNumber: 347,
        expirience: 2208,
        gold: 1873,
        resources: {
            Stick: 319,
            'Wooden arrow': 185,
            Pelt: 157,
            'Stone of Prime': 19,
        },
    },
    'Y 2#1': {
        regionName: 'Y 2#1',
        questsNumber: 85,
        successQuestsNumber: 68,
        expirience: 455,
        gold: 274,
        resources: {
            'Iron Ore': 103,
            'Scroll of Escape': 6,
            Wrapping: 3,
            Powder: 2,
            Stick: 1,
        },
    },
    'Y 4#1': {
        regionName: 'Y 4#1',
        questsNumber: 63,
        successQuestsNumber: 52,
        expirience: 358,
        gold: 216,
        resources: {
            Powder: 10,
            Wrapping: 4,
            Stick: 2,
            'Stone of Prime': 2,
        },
    },
    'Y 1#1': {
        regionName: 'Y 1#1',
        questsNumber: 58,
        successQuestsNumber: 44,
        expirience: 291,
        gold: 278,
        resources: {
            Stick: 54,
            'Fresh Grapes': 21,
            'Grape Juice': 7,
            'Grape Essence': 3,
        },
    },
    'GY 2': {
        regionName: 'GY 2',
        questsNumber: 41,
        successQuestsNumber: 30,
        expirience: 201,
        gold: 152,
        resources: {
            'Wooden arrow': 28,
            Bone: 16,
            'Poor Meat Cut': 7,
            Powder: 5,
            Thread: 4,
            Stick: 1,
        },
    },
    'Y 2#2': {
        regionName: 'Y 2#2',
        questsNumber: 31,
        successQuestsNumber: 26,
        expirience: 168,
        gold: 140,
        resources: {
            Thread: 33,
            'Wooden arrow': 21,
            Powder: 19,
            'Sour Mushroom': 15,
            'Forest Mushroom': 5,
        },
    },
    'GY 4': {
        regionName: 'GY 4',
        questsNumber: 27,
        successQuestsNumber: 23,
        expirience: 147,
        gold: 82,
        resources: {
            'Iron Ore': 15,
            Wrapping: 1,
            'Scroll of Escape': 1,
            Powder: 1,
        },
    },
    'Y 2#5': {
        regionName: 'Y 2#5',
        questsNumber: 25,
        successQuestsNumber: 18,
        expirience: 126,
        gold: 95,
        resources: {
            'Sour Mushroom': 4,
            Thread: 4,
            Powder: 2,
            Stick: 2,
            'Wooden arrow': 1,
            'Forest Mushroom': 1,
            Truffle: 1,
        },
    },
    'Y 1#5': {
        regionName: 'Y 1#5',
        questsNumber: 23,
        successQuestsNumber: 18,
        expirience: 123,
        gold: 63,
        resources: {
            'Iron Ore': 11,
            Wrapping: 1,
        },
    },
    'Y 1#2': {
        regionName: 'Y 1#2',
        questsNumber: 23,
        successQuestsNumber: 19,
        expirience: 122,
        gold: 102,
        resources: {
            Stick: 26,
            'Wooden arrow': 17,
            Pelt: 9,
            'Stone of Prime': 1,
        },
    },
    'Y 1#3': {
        regionName: 'Y 1#3',
        questsNumber: 20,
        successQuestsNumber: 16,
        expirience: 94,
        gold: 63,
        resources: {
            Pelt: 11,
            Powder: 10,
            'Goat Milk': 9,
            Wrapping: 4,
            'Iron Ore': 4,
            Thread: 3,
            'Goat Cheese': 2,
            'Soft Cheese': 2,
        },
    },
    'GY 3': {
        regionName: 'GY 3',
        questsNumber: 18,
        successQuestsNumber: 16,
        expirience: 105,
        gold: 123,
        resources: {
            Pelt: 14,
            Cloth: 7,
            'Mutton Cut': 6,
            Thread: 5,
            'Lamb Fillet': 4,
            Wrapping: 2,
        },
    },
    'Y 3#5': {
        regionName: 'Y 3#5',
        questsNumber: 17,
        successQuestsNumber: 14,
        expirience: 92,
        gold: 62,
        resources: {
            Stick: 4,
            'Common Apple': 1,
            'Wooden arrow': 1,
            'Stone of Prime': 1,
            'Enchanted Apple': 1,
        },
    },
    'Y 5#5': {
        regionName: 'Y 5#5',
        questsNumber: 15,
        successQuestsNumber: 14,
        expirience: 90,
        gold: 79,
        resources: {
            Bone: 4,
            Powder: 3,
            'Chicken Breast': 3,
            'Chicken Egg': 2,
        },
    },
    'Y 1#4': {
        regionName: 'Y 1#4',
        questsNumber: 15,
        successQuestsNumber: 11,
        expirience: 70,
        gold: 48,
        resources: {
            Wheat: 7,
            Powder: 6,
            Rye: 4,
            'Golden Barley': 2,
        },
    },
    'Y 2#4': {
        regionName: 'Y 2#4',
        questsNumber: 14,
        successQuestsNumber: 12,
        expirience: 91,
        gold: 56,
        resources: {},
    },
    'Y 4#4': {
        regionName: 'Y 4#4',
        questsNumber: 14,
        successQuestsNumber: 10,
        expirience: 70,
        gold: 82,
        resources: {
            Pelt: 7,
            'Mutton Cut': 5,
            Cloth: 3,
            Thread: 2,
            Wrapping: 2,
            'Lamb Fillet': 2,
        },
    },
    'Y 5#3': {
        regionName: 'Y 5#3',
        questsNumber: 13,
        successQuestsNumber: 12,
        expirience: 87,
        gold: 32,
        resources: {
            Thread: 2,
            'Iron Ore': 2,
            'Goat Cheese': 1,
            Wrapping: 1,
            Pelt: 1,
        },
    },
    'Y 3#1': {
        regionName: 'Y 3#1',
        questsNumber: 12,
        successQuestsNumber: 10,
        expirience: 58,
        gold: 55,
        resources: {
            Stick: 7,
            Pelt: 5,
            'Wooden arrow': 2,
        },
    },
    'Y 5#4': {
        regionName: 'Y 5#4',
        questsNumber: 11,
        successQuestsNumber: 9,
        expirience: 57,
        gold: 54,
        resources: {
            Stick: 2,
            Pelt: 1,
        },
    },
    'G 2#1': {
        regionName: 'G 2#1',
        questsNumber: 11,
        successQuestsNumber: 9,
        expirience: 61,
        gold: 71,
        resources: {
            Powder: 5,
            Wheat: 4,
            Rye: 2,
            Wrapping: 1,
            Stick: 1,
            'Golden Barley': 1,
        },
    },
    'YB 2': {
        regionName: 'YB 2',
        questsNumber: 11,
        successQuestsNumber: 6,
        expirience: 40,
        gold: 15,
        resources: {
            Pelt: 8,
            'Iron Ore': 4,
            Thread: 3,
            Powder: 3,
        },
    },
    'YB 4': {
        regionName: 'YB 4',
        questsNumber: 9,
        successQuestsNumber: 6,
        expirience: 40,
        gold: 49,
        resources: {
            Wheat: 4,
        },
    },
    'Y 5#1': {
        regionName: 'Y 5#1',
        questsNumber: 9,
        successQuestsNumber: 7,
        expirience: 49,
        gold: 43,
        resources: {
            Stick: 3,
            'Wooden arrow': 3,
            Pelt: 1,
        },
    },
    'YB 3': {
        regionName: 'YB 3',
        questsNumber: 8,
        successQuestsNumber: 7,
        expirience: 44,
        gold: 32,
        resources: {
            Powder: 8,
            Coal: 5,
        },
    },
    'Y 6#6': {
        regionName: 'Y 6#6',
        questsNumber: 7,
        successQuestsNumber: 5,
        expirience: 44,
        gold: 26,
        resources: {
            Bone: 2,
        },
    },
    'Y 3#6': {
        regionName: 'Y 3#6',
        questsNumber: 5,
        successQuestsNumber: 5,
        expirience: 45,
        gold: 40,
        resources: {
            'Fresh Grapes': 1,
            Stick: 1,
        },
    },
    'Y 5#2': {
        regionName: 'Y 5#2',
        questsNumber: 5,
        successQuestsNumber: 5,
        expirience: 36,
        gold: 41,
        resources: {
            Wrapping: 1,
        },
    },
    'Y 6#1': {
        regionName: 'Y 6#1',
        questsNumber: 4,
        successQuestsNumber: 4,
        expirience: 39,
        gold: 21,
        resources: {
            'Poor Meat Cut': 2,
            Powder: 1,
            Pelt: 1,
            'Wooden arrow': 1,
        },
    },
    'G 3#1': {
        regionName: 'G 3#1',
        questsNumber: 3,
        successQuestsNumber: 2,
        expirience: 12,
        gold: 8,
        resources: {
            Wheat: 4,
            Powder: 2,
        },
    },
    'Y 6#5': {
        regionName: 'Y 6#5',
        questsNumber: 2,
        successQuestsNumber: 1,
        expirience: 9,
        gold: 3,
        resources: {
            'Fresh Grapes': 1,
        },
    },
    'G 1#1': {
        regionName: 'G 1#1',
        questsNumber: 2,
        successQuestsNumber: 2,
        expirience: 18,
        gold: 7,
        resources: {},
    },
    'G 5#1': {
        regionName: 'G 5#1',
        questsNumber: 1,
        successQuestsNumber: 1,
        expirience: 8,
        gold: 5,
        resources: {
            'Wooden arrow': 1,
        },
    },
}
